ALTER TABLE adm_competencies DROP FOREIGN KEY fk_adm_competencies_adm_codes ;
ALTER TABLE adm_branches DROP FOREIGN KEY `fk_ADM_BRNACHES_COUNTRY` ;
ALTER TABLE `ADM_PROJECTS` DROP FOREIGN KEY `fk_ADM_PROJECTS_CYC` ;
ALTER TABLE `ADM_PROJECTS` DROP FOREIGN KEY `fk_ADM_PROJECTS_TYPE` ;
ALTER TABLE `ADM_PROJECTS` DROP FOREIGN KEY `fk_ADM_PROJECTS_R_UNIT` ;
ALTER TABLE `ADM_UNITS` DROP FOREIGN KEY `fk_ADM_UNITS` ;
